#!/bin/sh
# wrapper to simply pass all to aic-lib
# defined as 2 letter commands 676 options (+ flags)
# show help if no args
[ $# -eq 0 ] && cat << EOF && exit 0
archinstall-contrib

Commands:
  rs                                - rescue    Inject rescue mod into archinstall

Usage: mods <something>
EOF

##commandsm##
[ "$1" = "rs" ] && set -- "rescue" "${@:2}"


cmd="/usr/lib/ac/$1"
[ ! -f "$cmd" ] && echo "Error: Unknown command '$1'" && exit 1
"$cmd" "${@:2}"
