#!/bin/sh
# usage collab <user> <branch> <fork-name>
# examples
# collab archlinux master archinstall
# collab h8d13 dot-algo archinstall-patch

# ensure we clone fresh
if [ -d "$3" ]; then
    rm -rf "$3"; echo "Cleaned $3"
fi

# less typing more working
dev_flags=(--debug --verbose)

provider="https://github.com"
git clone -b "$2" "$provider/$1/$3"

cd $3 || exit 1
sudo python -m archinstall "${dev_flags[@]}"